# Generated by Django 2.2.2 on 2019-06-05 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='rwa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('addr', models.CharField(max_length=200)),
                ('pincode', models.IntegerField()),
                ('subscriptionType', models.CharField(max_length=100)),
                ('subscriptionId', models.IntegerField()),
            ],
        ),
    ]
